import va_gen as va

# input template file path
template_path = "./template.va"
# output file path
save_path = "./generate.va"

# the comment in the veriloga file
comment = "This file is generated by the VA_GEN ."
# the module name
module_name = "DSP_signtb"

# the expected output signals
# signal-name | signal-width | waves-length | waves-value
signal_args = [
    ["DIN", 12, 11, [17, 3, 256, 4, 0, 0, 0, 0, 0, 0, 0]],
    ["SEL", 1, 11, [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0]],
    ["MODE", 1, 11, [1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0]],
    ["WL", 8, 11, [1, 2, 4, 8, 1, 2, 4, 8, 0, 16, 16]],
    ["EN", 4, 11, [0, 0, 0, 0, 0, 1, 2, 4, 8, 0, 0]],
]

if __name__ == "__main__":
    generator = va.VaGenerator(template_path)
    generator.generate_veriloga(module_name, comment, signal_args, save_path)
